"""add_percentage_of_ath

Revision ID: 5f1cd558d1f0
Revises: 42f600a0227a
Create Date: 2023-08-23 13:50:35.776323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1cd558d1f0'
down_revision = '42f600a0227a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage_of_ath', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_column('percentage_of_ath')

    # ### end Alembic commands ###
